= 
:allow-uri-read: 


[role="tabbed-block"]
====
.AWS / VMC
--
이 섹션에서는 AWS SDDC에서 VMware Cloud를 설정하고 관리하는 방법과 NetApp 스토리지를 연결하는 데 사용 가능한 옵션과 함께 사용하는 방법을 설명합니다.


NOTE: 게스트 내 스토리지는 Cloud Volumes ONTAP AWS VMC에 연결하는 데 지원되는 유일한 방법입니다.

설정 과정은 다음 단계로 나눌 수 있습니다.

* AWS용 VMware Cloud 배포 및 구성
* VMware Cloud를 FSx ONTAP 에 연결


자세한 내용을 보려면link:../vmware/vmw-aws-vmc-setup.html["VMC 구성 단계"] .

자세한 내용을 보려면link:../vmware/vmw-aws-vmc-setup.html["VMC 구성 단계"] .

--
.Azure / AVS
--
이 섹션에서는 Azure VMware Solution을 설정하고 관리하는 방법과 NetApp 스토리지를 연결하는 데 사용 가능한 옵션과 함께 사용하는 방법을 설명합니다.


NOTE: 게스트 내 스토리지는 Cloud Volumes ONTAP Azure VMware Solution에 연결하는 데 지원되는 유일한 방법입니다.

설정 과정은 다음 단계로 나눌 수 있습니다.

* 리소스 공급자를 등록하고 프라이빗 클라우드를 생성하세요
* 새 ExpressRoute 가상 네트워크 게이트웨이 또는 기존 ExpressRoute 가상 네트워크 게이트웨이에 연결
* 네트워크 연결을 검증하고 프라이빗 클라우드에 액세스합니다.


자세한 내용을 보려면link:../vmware/vmw-azure-avs-setup.html["AVS 구성 단계"] .

자세한 내용을 보려면link:../vmware/vmw-azure-avs-setup.html["AVS 구성 단계"] .

--
.GCP/GCVE
--
이 섹션에서는 GCVE를 설정하고 관리하는 방법과 NetApp 스토리지 연결에 사용 가능한 옵션과 함께 사용하는 방법을 설명합니다.


NOTE: 게스트 내 스토리지는 Cloud Volumes ONTAP 및 Google Cloud NetApp Volumes GCVE에 연결하는 데 지원되는 유일한 방법입니다.

설정 과정은 다음 단계로 나눌 수 있습니다.

* GCVE 배포 및 구성
* GCVE에 대한 개인 액세스 활성화


자세한 내용을 보려면link:../vmware/vmw-gcp-gcve-setup.html["GCVE 구성 단계"] .

자세한 내용을 보려면link:../vmware/vmw-gcp-gcve-setup.html["GCVE 구성 단계"] .

--
====