---
sidebar: sidebar 
permalink: vmware/evs-protect-fsxn-intro.html 
keywords: Amazon, AWS, EVS, Elastic VMware Service, ONTAP, FSx 
summary: '이 가이드에서는 NetApp SnapCenter® Plug-in for VMware vSphere(SCV) 백업 및 복구 솔루션을 사용하여 FSx for ONTAP 네트워크 파일 시스템(NFS) 및 iSCSI Amazon EVS 데이터스토어와 관련 VM을 보호하기 위한 간단한 배포 방법을 설명합니다.' 
---
= Amazon Elastic VMware Service를 사용하여 Amazon FSx for NetApp ONTAP 데이터스토어를 NetApp SnapCenter Plug-in for VMware로 보호하는 방법
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
이 가이드에서는 NetApp SnapCenter® Plug-in for VMware vSphere(SCV) 백업 및 복구 솔루션을 사용하여 FSx for ONTAP 네트워크 파일 시스템(NFS) 및 iSCSI Amazon EVS 데이터스토어와 관련 VM을 보호하기 위한 간단한 배포 방법을 설명합니다.



== 소개

Amazon FSx for NetApp ONTAP(FSx for ONTAP) 기반 Amazon Elastic VMware Service(Amazon EVS)용 보조 데이터스토어는 nConnect 활용, Amazon Virtual Private Cloud(Amazon VPC) 피어링, 데이터스토어 마운트당 여러 네트워크 연결 사용과 같은 고성능 워크로드와 스토리지 집약적인 워크로드를 모두 실행하는 데 탁월한 솔루션을 제공합니다.

이 기능을 통해 고객은 vSAN(가상 스토리지 영역 네트워크)에서 제공하는 로컬 인스턴스 스토리지의 한계를 극복하고, 컴퓨팅과 독립적으로 스토리지를 확장하며, 전체 총 소유 비용을 절감할 수 있습니다. 총 소유 비용(TCO) 이점 외에도 FSx for ONTAP은 온프레미스 ONTAP® 고객에게 익숙한 엔터프라이즈급 기능을 갖춘 Amazon EVS를 제공하여 배포를 최적화하고 간소화하는 데 도움을 줍니다. FSx for ONTAP을 사용하면 가상 머신(VM), 데이터스토어 및 가상 머신 디스크(VMDK)의 백업 및 복원 작업을 지원하는 NetApp® Snapshot™, SnapMirror® 및 SnapVault® 기술에 액세스할 수 있습니다. 주요 기능 중 하나는 Snapshot 기반 보호입니다.



== 개요

조직이 규모를 확장하고 환경을 통합함에 따라 워크로드와 기본 스토리지를 보호해야 할 필요성이 점점 더 중요해집니다. SCV를 사용하면 Amazon EVS vSphere 클라이언트에서 데이터스토어와 가상 머신을 직접 백업할 수 있습니다.



== 이 가이드의 목적

이 가이드에서는 SCV를 사용하여 Amazon EVS용 FSx for ONTAP 데이터스토어를 보호하는 방법을 안내합니다. VM 및 데이터베이스 보호 시나리오와 복원 방법도 함께 제공됩니다.



== 대상

이 튜토리얼은 VMware vSphere, Amazon EVS, AWS 콘솔, FSx for ONTAP 에 익숙한 클라우드 아키텍트와 클라우드 관리자를 대상으로 합니다.



== 배포 및 구성을 위한 고급 단계

다음은 Amazon FSx for NetApp ONTAP에서 VM 및 데이터 저장소를 보호하기 위해 SnapCenter Plug-in for VMware vSphere를 배포하고 구성하는 주요 단계입니다.

. SCV Open Virtual Appliance(OVA)를 다운로드합니다.
. vSphere Client 자격 증명을 사용하여 Amazon EVS에 로그인합니다.
. VMware 배포 마법사를 시작하려면 Open Virtualization Format(OVF) 템플릿을 배포하십시오.
. 플러그인에 액세스하려면 메뉴에서 SnapCenter Plug-in for VMware를 선택하십시오.
. 스토리지를 추가합니다.
. 백업 정책을 생성합니다.
. 리소스 그룹을 생성합니다.
. 리소스 그룹을 백업합니다.
. 전체 가상 머신 또는 특정 가상 디스크나 게스트 파일을 복원합니다.

