---
sidebar: sidebar 
permalink: vmware/vmw-hybrid-use-cases.html 
keywords: NetApp Solutions, ehc, enterprise hybrid cloud, use case, hyperscalers, vmware 
summary:  
---
= VMware를 활용한 NetApp 하이브리드 멀티클라우드 사용 사례
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
하이브리드 클라우드 또는 클라우드 우선 배포를 계획할 때 IT 조직에 중요한 사용 사례에 대한 개요입니다.



== 인기 있는 사용 사례

사용 사례는 다음과 같습니다.

* 재해 복구,
* 데이터 센터 유지 관리 중 호스팅 작업, * 로컬 데이터 센터에 프로비저닝된 것 이상의 추가 리소스가 필요한 급격한 버스트
* VMware 사이트 확장,
* 클라우드로의 빠른 마이그레이션
* 개발/테스트 및
* 클라우드 보완 기술을 활용한 앱의 현대화.


이 문서 전체에서 클라우드 워크로드 참조는 VMware 사용 사례를 사용하여 자세히 설명됩니다.  이러한 사용 사례는 다음과 같습니다.

* 보호(재해 복구 및 백업/복원 모두 포함)
* 이주하다
* 연장하다




=== IT 여정 내부

대부분의 조직은 변혁과 현대화를 향한 여정에 나섰습니다.  이러한 과정의 일환으로 기업들은 클라우드의 이점을 활용하고 마이그레이션 프로세스를 가능한 한 원활하게 만드는 방법을 모색하면서 기존 VMware 투자를 활용하려고 노력하고 있습니다.  이러한 접근 방식을 사용하면 데이터가 이미 클라우드에 있으므로 현대화 작업이 매우 수월해집니다.

이 시나리오에 대한 가장 쉬운 답은 각 하이퍼스케일러에서 VMware가 제공하는 제품입니다.  NetApp Cloud Volumes와 마찬가지로 VMware는 온프레미스 VMware 환경을 모든 클라우드로 이동하거나 확장하는 방법을 제공하여 클라우드에서 기본적으로 워크로드를 실행하면서 기존 온프레미스 자산, 기술 및 도구를 유지할 수 있습니다.  이렇게 하면 서비스 중단이나 IP 변경이 필요 없기 때문에 위험이 줄어들고, IT 팀은 기존 기술과 도구를 사용하여 사내에서처럼 운영할 수 있습니다.  이를 통해 클라우드 마이그레이션이 가속화되고 하이브리드 멀티클라우드 아키텍처로의 전환이 훨씬 더 원활해질 수 있습니다.



=== 보충 NFS 스토리지 옵션의 중요성 이해

VMware는 모든 클라우드에서 모든 고객에게 고유한 하이브리드 기능을 제공하지만, 제한된 보충 NFS 스토리지 옵션으로 인해 스토리지 사용량이 많은 작업 부하가 있는 조직에서는 유용성이 제한됩니다.  스토리지는 호스트에 직접 연결되므로 스토리지를 확장하는 유일한 방법은 호스트를 추가하는 것입니다. 그러면 스토리지를 많이 사용하는 작업의 경우 비용이 35~40% 이상 증가할 수 있습니다.  이러한 작업에는 추가 마력이 아닌 추가 저장 공간만 필요합니다.  하지만 이는 추가 호스트 비용을 지불해야 한다는 것을 의미합니다.

다음 시나리오를 생각해 보겠습니다.

어떤 고객은 CPU와 메모리에 호스트 5개만 필요하지만 저장 공간이 많이 필요하여 저장 공간 요구 사항을 충족하려면 호스트 12개가 필요합니다.  이러한 요구 사항은 저장 용량만 늘리면 되는데 추가 마력을 구매해야 하므로 결국 재정적 규모가 실제로 커지는 결과를 초래합니다.

클라우드 도입 및 마이그레이션을 계획할 때는 항상 가장 좋은 접근 방식을 평가하고 총 투자를 줄이는 가장 쉬운 경로를 선택하는 것이 중요합니다.  모든 애플리케이션 마이그레이션에 가장 일반적이고 쉬운 방법은 리호스팅(리프트 앤 시프트라고도 함)인데, 이때는 가상 머신(VM)이나 데이터 변환이 없습니다.  vSAN을 보완하는 동시에 VMware 소프트웨어 정의 데이터 센터(SDDC)와 함께 NetApp Cloud Volumes를 사용하면 간편한 리프트 앤 시프트 옵션을 제공합니다.
