---
sidebar: sidebar 
permalink: vmware/vmw-hybrid-summary.html 
keywords: NetApp Solutions, hybrid, Multicloud, enterprise hybrid cloud, hyperscalers, vmware 
summary:  
---
= 요약 및 결론: VMware와 NetApp 하이브리드 멀티클라우드를 함께 사용하는 이유
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
주요 하이퍼스케일러를 위한 VMware 솔루션과 함께 NetApp Cloud Volumes는 하이브리드 클라우드를 활용하고자 하는 조직에 큰 잠재력을 제공합니다.  이 섹션의 나머지 부분에서는 NetApp Cloud Volumes를 통합하면 진정한 하이브리드 멀티클라우드 기능이 가능해지는 것을 보여주는 사용 사례를 제공합니다.



== 사용 사례 #1: 스토리지 최적화

RVtools 출력을 사용하여 크기 조정 작업을 수행할 때 마력(vCPU/vMem) 규모가 스토리지와 평행하다는 것이 항상 분명합니다.  많은 경우, 조직에서는 클러스터의 크기가 필요한 마력보다 훨씬 큰 저장 공간에 의존하게 됩니다.

NetApp Cloud Volumes를 통합하면 조직은 재플랫폼, IP 변경, 아키텍처 변경 없이 간단한 마이그레이션 방식으로 vSphere 기반 클라우드 솔루션을 실현할 수 있습니다.  또한, 이 최적화를 통해 vSphere에 필요한 최소한의 호스트 수로 유지하면서 스토리지 공간을 확장할 수 있으며, 스토리지 계층 구조, 보안 또는 사용 가능한 파일은 변경되지 않습니다.  이를 통해 배포를 최적화하고 전체 TCO를 35~45% 절감할 수 있습니다.  이러한 통합을 통해 몇 초 만에 웜 스토리지에서 프로덕션 수준의 성능으로 스토리지를 확장할 수도 있습니다.



== 사용 사례 #2: 클라우드 마이그레이션

기업들은 여러 가지 이유로 온프레미스 데이터 센터에서 퍼블릭 클라우드로 애플리케이션을 마이그레이션해야 하는 압박을 받고 있습니다. 임대 만료가 다가오고, 자본 지출(capex)에서 운영 지출(opex)로 전환하라는 재무 지침이 있고, 모든 것을 클라우드로 이전하라는 상향식 명령이 있기 때문입니다.

속도가 중요한 경우 간소화된 마이그레이션 방식만이 실행 가능합니다. 클라우드의 특정 IaaS 플랫폼에 맞게 애플리케이션을 재플랫폼하고 리팩토링하는 작업은 느리고 비용이 많이 들며, 종종 몇 달이 걸리기 때문입니다.  게스트 연결 스토리지를 위한 대역폭 효율적인 SnapMirror 복제(애플리케이션 일관성 있는 스냅샷 복사본 및 HCX와 함께 RDM, 클라우드별 마이그레이션(예: Azure Migrate) 또는 VM 복제를 위한 타사 제품 포함)와 NetApp Cloud Volumes를 결합하면 이러한 전환은 시간이 많이 소요되는 I/O 필터 메커니즘에 의존하는 것보다 훨씬 더 쉽습니다.



== 사용 사례 #3: 데이터 센터 확장

계절적 수요 급증이나 꾸준한 유기적 성장으로 인해 데이터 센터가 용량 한계에 도달하면 NetApp Cloud Volumes와 함께 클라우드 호스팅 VMware로 이전하는 것이 쉬운 솔루션입니다.  NetApp Cloud Volumes를 활용하면 가용성 영역 전반에서 높은 가용성과 동적 확장 기능을 제공하여 스토리지를 매우 쉽게 생성, 복제 및 확장할 수 있습니다.  NetApp Cloud Volumes를 활용하면 스트레치 클러스터의 필요성을 극복하여 호스트 클러스터 용량을 최소화하는 데 도움이 됩니다.



== 사용 사례 #4: 클라우드로의 재해 복구

기존 방식에서는 재해가 발생하면 클라우드에 복제된 VM을 복원하기 전에 클라우드 자체의 하이퍼바이저 플랫폼으로 변환해야 했습니다. 위기 상황에서 처리할 작업이 아니었습니다.

온프레미스의 SnapCenter 및 SnapMirror 복제와 퍼블릭 클라우드 가상화 솔루션을 함께 사용하여 게스트 연결 스토리지에 NetApp Cloud Volumes를 사용하면 재해 복구를 위한 더 나은 접근 방식을 고안하여 VM 복제본을 클라우드 특정 복구 도구(예: Azure Site Recovery)나 Veeam과 같은 동등한 타사 도구와 함께 완전히 일관된 VMware SDDC 인프라에서 복구할 수 있습니다.  이 접근 방식을 사용하면 재해 복구 훈련을 수행하고 랜섬웨어로부터 신속하게 복구할 수도 있습니다.  이를 통해 필요에 따라 호스트를 추가하여 테스트나 재해 발생 시 전체 운영 환경으로 확장할 수도 있습니다.



== 사용 사례 #5: 애플리케이션 현대화

애플리케이션이 퍼블릭 클라우드에 저장된 후, 조직에서는 수백 개의 강력한 클라우드 서비스를 활용하여 이를 현대화하고 확장하고자 할 것입니다.  NetApp Cloud Volumes를 사용하면 애플리케이션 데이터가 vSAN에 갇히지 않고 Kubernetes를 포함한 다양한 사용 사례에서 데이터 이동성이 가능하므로 현대화가 쉽게 진행됩니다.



== 결론

전체 클라우드 또는 하이브리드 클라우드를 타겟으로 삼는지 여부에 관계없이 NetApp Cloud Volumes는 파일 서비스 및 블록 프로토콜과 함께 애플리케이션 워크로드를 배포하고 관리하는 탁월한 옵션을 제공하며, 데이터 요구 사항을 애플리케이션 계층에 원활하게 전달하여 TCO를 절감합니다.

어떤 사용 사례든 NetApp Cloud Volumes와 함께 원하는 클라우드/하이퍼스케일러를 선택하여 클라우드의 이점을 빠르게 실현하고, 온프레미스와 여러 클라우드에서 일관된 인프라와 운영을 구현하고, 워크로드를 양방향으로 이동시키고, 엔터프라이즈급 용량과 성능을 확보하세요.

이는 저장소를 연결하는 데 사용되는 것과 동일한 익숙한 프로세스 및 절차입니다.  새로운 이름으로 변경된 것은 단지 데이터의 위치일 뿐이며, 도구와 프로세스는 모두 동일하게 유지되며 NetApp Cloud Volumes는 전반적인 배포를 최적화하는 데 도움이 됩니다.
