---
sidebar: sidebar 
permalink: vmware/vmw-azure-avs-nfs-ds-overview.html 
keywords:  
summary:  
---
= ANF 데이터 저장소 솔루션 개요
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
모든 성공적인 조직은 변화와 현대화의 길을 걷고 있습니다.  이 과정의 일환으로 기업은 일반적으로 기존 VMware 투자를 활용하면서 클라우드의 이점을 활용하고 마이그레이션, 버스트, 확장 및 재해 복구 프로세스를 최대한 원활하게 만드는 방법을 모색합니다.  클라우드로 마이그레이션하는 고객은 탄력성과 폭발성, 데이터 센터 종료, 데이터 센터 통합, 수명 종료 시나리오, 합병, 인수 등의 문제를 평가해야 합니다.  각 조직이 채택하는 접근 방식은 해당 사업 우선순위에 따라 달라질 수 있습니다.  클라우드 기반 운영을 선택할 때 적절한 성능과 최소한의 방해 요소를 갖춘 저비용 모델을 선택하는 것이 중요한 목표입니다.  올바른 플랫폼을 선택하는 것과 함께 스토리지와 워크플로우 오케스트레이션은 클라우드 배포와 탄력성의 힘을 최대한 활용하는 데 특히 중요합니다.



== 사용 사례

Azure VMware 솔루션은 고객에게 고유한 하이브리드 기능을 제공하지만, 기본 스토리지 옵션이 제한적이어서 스토리지 사용량이 많은 작업 부하를 가진 조직에서는 유용성이 제한됩니다.  스토리지는 호스트에 직접 연결되므로 스토리지를 확장하는 유일한 방법은 호스트를 추가하는 것인데, 스토리지를 많이 사용하는 작업의 경우 비용이 35~40% 이상 증가할 수 있습니다.  이러한 작업에는 추가 마력이 아닌 추가 저장 용량이 필요한데, 이는 추가 호스트 비용을 지불해야 한다는 것을 의미합니다.

다음 시나리오를 생각해 보겠습니다. 어떤 고객은 성능(vCPU/vMem)을 위해 6개의 호스트가 필요하지만, 저장 용량도 상당히 필요합니다.  평가에 따르면 저장 요구 사항을 충족하려면 12개의 호스트가 필요합니다.  실제로 필요한 것이 저장 공간뿐인데도 추가 마력을 모두 구매해야 하므로 전반적인 TCO가 증가합니다.  이는 마이그레이션, 재해 복구, 버스팅, 개발/테스트 등 모든 사용 사례에 적용할 수 있습니다.

Azure VMware Solution의 또 다른 일반적인 사용 사례는 재해 복구(DR)입니다.  대부분의 조직은 완벽한 재해 복구 전략이 없으며, 재해 복구만을 위해 고스트 데이터 센터를 운영하는 것을 정당화하는 데 어려움을 겪을 수 있습니다.  관리자는 파일럿 라이트 클러스터나 주문형 클러스터를 통해 제로 풋프린트 DR 옵션을 모색할 수 있습니다.  그러면 추가 호스트를 추가하지 않고도 스토리지를 확장할 수 있어 매력적인 옵션이 될 수 있습니다.

따라서 요약하자면, 사용 사례는 두 가지 방법으로 분류할 수 있습니다.

* ANF 데이터 저장소를 사용하여 스토리지 용량 확장
* 온프레미스 또는 Azure 지역 내에서 소프트웨어 정의 데이터 센터(SDDC) 간 비용 최적화된 복구 워크플로를 위한 재해 복구 대상으로 ANF 데이터 저장소를 사용하는 방법. 이 가이드에서는 Azure NetApp Files 사용하여 데이터 저장소에 최적화된 스토리지(현재 공개 미리 보기)와 Azure VMware 솔루션에서 동급 최고의 데이터 보호 및 재해 복구 기능을 제공하는 방법에 대한 통찰력을 제공합니다. 이를 통해 vSAN 스토리지에서 스토리지 용량을 오프로드할 수 있습니다.



NOTE: ANF 데이터 저장소 사용에 대한 추가 정보는 해당 지역의 NetApp 또는 Microsoft 솔루션 설계자에게 문의하세요.



== Azure의 VMware Cloud 옵션



=== Azure VMware 솔루션

Azure VMware 솔루션(AVS)은 Microsoft Azure 퍼블릭 클라우드 내에서 완벽하게 작동하는 VMware SDDC를 제공하는 하이브리드 클라우드 서비스입니다.  AVS는 Microsoft에서 완벽하게 관리하고 지원하며 VMware에서 검증한 자체 솔루션으로, Azure 인프라를 사용합니다.  따라서 고객은 컴퓨팅 가상화를 위해 VMware ESXi, 하이퍼 컨버지드 스토리지를 위해 vSAN, 네트워킹 및 보안을 위해 NSX를 얻는 동시에 Microsoft Azure의 글로벌 입지, 동급 최고의 데이터 센터 시설, 풍부한 기본 Azure 서비스 및 솔루션 생태계와의 근접성을 활용할 수 있습니다.  Azure VMware Solution SDDC와 Azure NetApp Files 결합하면 최소한의 네트워크 지연으로 최고의 성능을 제공합니다.

사용하는 클라우드에 관계없이 VMware SDDC가 배포되면 초기 클러스터에는 다음 구성 요소가 포함됩니다.

* 관리를 위한 vCenter 서버 어플라이언스와 함께 컴퓨팅 가상화를 위한 VMware ESXi 호스트.
* 각 ESXi 호스트의 물리적 스토리지 자산을 통합한 VMware vSAN 하이퍼 컨버지드 스토리지입니다.
* 가상 네트워킹 및 보안을 위한 VMware NSX와 관리를 위한 NSX Manager 클러스터.




== 결론

전체 클라우드 또는 하이브리드 클라우드를 타겟으로 삼는지 여부에 관계없이 Azure NetApp 파일은 데이터 요구 사항을 애플리케이션 계층에 원활하게 전달하여 TCO를 줄이는 동시에 파일 서비스와 함께 애플리케이션 워크로드를 배포하고 관리할 수 있는 탁월한 옵션을 제공합니다.  어떤 사용 사례든 Azure NetApp Files 와 함께 Azure VMware 솔루션을 선택하면 클라우드의 이점을 빠르게 실현하고, 온프레미스와 여러 클라우드에서 일관된 인프라와 운영을 구현하고, 워크로드를 양방향으로 이동시키고, 엔터프라이즈급 용량과 성능을 얻을 수 있습니다.  저장소를 연결하는 데 사용되는 익숙한 프로세스와 절차와 동일합니다.  기억하세요. 새로운 이름과 함께 데이터의 위치만 변경되었을 뿐, 도구와 프로세스는 모두 동일하게 유지되며 Azure NetApp Files 전반적인 배포를 최적화하는 데 도움이 됩니다.



== 테이크아웃

이 문서의 주요 내용은 다음과 같습니다.

* 이제 Azure NetApp Files AVS SDDC의 데이터 저장소로 사용할 수 있습니다.
* 애플리케이션 응답 시간을 단축하고 가용성을 높여 필요할 때 필요한 위치에서 워크로드 데이터에 액세스할 수 있도록 합니다.
* 간단하고 즉각적인 크기 조정 기능으로 vSAN 스토리지의 전반적인 복잡성을 단순화합니다.
* 동적 재구성 기능을 사용하여 미션 크리티컬 워크로드에 대한 성능을 보장합니다.
* Azure VMware Solution Cloud가 대상이라면 Azure NetApp Files 최적화된 배포를 위한 적합한 스토리지 솔루션입니다.




== 추가 정보를 찾을 수 있는 곳

이 문서에 설명된 정보에 대해 자세히 알아보려면 다음 웹사이트 링크를 참조하세요.

* Azure VMware 솔루션 설명서
+
https://docs.microsoft.com/en-us/azure/azure-vmware/["https://docs.microsoft.com/en-us/azure/azure-vmware/"^]

* Azure NetApp Files 설명서
+
https://docs.microsoft.com/en-us/azure/azure-netapp-files/["https://docs.microsoft.com/en-us/azure/azure-netapp-files/"^]

* Azure NetApp Files 데이터 저장소를 Azure VMware Solution 호스트에 연결(미리 보기)
+
https://docs.microsoft.com/en-us/azure/azure-vmware/attach-azure-netapp-files-to-azure-vmware-solution-hosts?tabs=azure-portal/["https://docs.microsoft.com/en-us/azure/azure-vmware/attach-azure-netapp-files-to-azure-vmware-solution-hosts?tabs=azure-portal/"^]


