---
sidebar: sidebar 
permalink: google/gcp-gcnv-multiprotocol.html 
keywords: access control, user mapping, permission model 
summary: Google Cloud NetApp Volumes 적절한 이중 프로토콜 액세스 권한을 유지하면서 SMB 및 NFS 클라이언트 모두와 동일한 데이터 세트를 공유할 수 있는 기능을 제공합니다.  이는 프로토콜 간의 ID 매핑을 조정하고 중앙 집중식 백엔드 LDAP 서버를 사용하여 UNIX ID를 Google Cloud NetApp Volumes 에 제공함으로써 수행됩니다.  Windows Active Directory를 사용하면 Windows 사용자와 UNIX 사용자 모두에게 사용 편의성을 제공할 수 있습니다. 
---
= 듀얼 프로토콜/멀티 프로토콜
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Google Cloud NetApp Volumes 적절한 액세스 권한을 유지하면서 SMB 및 NFS 클라이언트 모두에 동일한 데이터 세트를 공유하는 기능을 제공합니다.(https://cloud.google.com/architecture/partners/netapp-cloud-volumes/managing-dual-protocol-access["듀얼 프로토콜"^] ).  이는 프로토콜 간의 ID 매핑을 조정하고 중앙 집중식 백엔드 LDAP 서버를 사용하여 UNIX ID를 Google Cloud NetApp Volumes 에 제공함으로써 수행됩니다.  Windows Active Directory를 사용하면 Windows 사용자와 UNIX 사용자 모두에게 사용 편의성을 제공할 수 있습니다.



== 접근 제어

* *공유 접근 제어.*  어떤 클라이언트 및/또는 사용자와 그룹이 NAS 공유에 액세스할 수 있는지 확인합니다.  NFS의 경우, 내보내기 정책과 규칙은 클라이언트의 내보내기 액세스를 제어합니다.  NFS 내보내기는 Google Cloud NetApp Volumes 인스턴스에서 관리됩니다.  SMB는 CIFS/SMB 공유와 공유 ACL을 활용하여 사용자 및 그룹 수준에서 보다 세부적인 제어를 제공합니다.  https://library.netapp.com/ecmdocs/ECMP1401220/html/GUID-C1772CDF-8AEE-422B-AB87-CFCB7E50FF94.html [MMC/Computer Management^]를 사용하여 SMB 클라이언트에서 공유 수준 ACL을 구성할 수 있습니다. Google Cloud NetApp Volumes 인스턴스에 대한 관리자 권한이 있는 계정이 필요합니다(링크:gcp-gcnv-smb.html#로컬/BUILTIN 관리자/백업 권한이 있는 계정["로컬/BUILTIN 관리자/백업 권한이 있는 계정"] 섹션 참조).
* *파일 접근 제어.*  파일 또는 폴더 수준에서 권한을 제어하며 항상 NAS 클라이언트에서 관리합니다.  NFS 클라이언트는 기존 모드 비트(rwx) 또는 NFSv4 ACL을 활용할 수 있습니다.  SMB 클라이언트는 NTFS 권한을 활용합니다.


NFS와 SMB 모두에 데이터를 제공하는 볼륨에 대한 액세스 제어는 사용 중인 프로토콜에 따라 달라집니다.  이중 프로토콜을 사용한 권한에 대한 정보는 "섹션"을 참조하세요.<<권한 모델>> ."



== 사용자 매핑

클라이언트가 볼륨에 액세스하면 Google Cloud NetApp Volumes 들어오는 사용자를 반대 방향의 유효한 사용자에 매핑하려고 시도합니다.  이는 프로토콜 전반에 걸쳐 적절한 액세스가 이루어졌는지 확인하고 액세스를 요청한 사용자가 실제로 주장하는 사람인지 확인하는 데 필요합니다.

예를 들어, Windows 사용자가 다음과 같은 경우 `joe` SMB를 통해 UNIX 권한이 있는 볼륨에 액세스를 시도하면 Google Cloud NetApp Volumes 검색을 수행하여 해당 UNIX 사용자를 찾습니다. `joe` .  만약 존재한다면 Windows 사용자로 SMB 공유에 쓰여진 파일 `joe` UNIX 사용자로 나타납니다 `joe` NFS 클라이언트에서.

또는 UNIX 사용자가 다음과 같은 경우 `joe` Windows 권한으로 Google Cloud NetApp Volumes 볼륨에 액세스를 시도하는 경우 UNIX 사용자는 유효한 Windows 사용자에 매핑할 수 있어야 합니다.  그렇지 않으면 볼륨에 대한 액세스가 거부됩니다.

현재 LDAP를 사용한 외부 UNIX ID 관리에는 Active Directory만 지원됩니다.  이 서비스에 대한 액세스 구성에 대한 자세한 내용은 다음을 참조하세요. https://cloud.google.com/architecture/partners/netapp-cloud-volumes/creating-smb-volumes["AD 연결 생성"^] .



== 권한 모델

이중 프로토콜 설정을 사용하는 경우 Google Cloud NetApp Volumes 볼륨의 보안 스타일을 활용하여 ACL 유형을 결정합니다.  이러한 보안 스타일은 지정된 NAS 프로토콜에 따라 설정되며, 이중 프로토콜의 경우 Google Cloud NetApp Volumes 볼륨을 생성할 때 선택합니다.

* NFS만 사용하는 경우 Google Cloud NetApp Volumes 볼륨은 UNIX 권한을 사용합니다.
* SMB만 사용하는 경우 Google Cloud NetApp Volumes 볼륨은 NTFS 권한을 사용합니다.


듀얼 프로토콜 볼륨을 생성하는 경우 볼륨 생성 시 ACL 스타일을 선택할 수 있습니다.  이러한 결정은 원하는 권한 관리에 따라 내려져야 합니다.  사용자가 Windows/SMB 클라이언트에서 권한을 관리하는 경우 NTFS를 선택하세요.  사용자가 NFS 클라이언트와 chmod/chown을 선호하는 경우 UNIX 보안 스타일을 사용하세요.
