---
sidebar: sidebar 
permalink: google/gcp-gcnv-arch-overview.html 
keywords: architecture overview, control plane, data plane 
summary: 클라우드 솔루션을 신뢰하려면 아키텍처와 보안 방식을 이해해야 합니다.  이 섹션에서는 Google의 Google Cloud NetApp Volumes 아키텍처의 다양한 측면을 설명하여 데이터 보안에 대한 잠재적 우려를 완화하는 데 도움을 주고, 가장 안전한 배포를 위해 추가 구성 단계가 필요할 수 있는 영역을 설명합니다. 
---
= 개요
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
클라우드 솔루션을 신뢰하려면 아키텍처와 보안 방식을 이해해야 합니다.  이 섹션에서는 Google의 Google Cloud NetApp Volumes 아키텍처의 다양한 측면을 설명하여 데이터 보안에 대한 잠재적 우려를 완화하는 데 도움을 주고, 가장 안전한 배포를 위해 추가 구성 단계가 필요할 수 있는 영역을 설명합니다.

Google Cloud NetApp Volumes 의 일반 아키텍처는 제어 평면과 데이터 평면이라는 두 가지 주요 구성 요소로 나눌 수 있습니다.



== 제어 평면

Google Cloud NetApp Volumes 의 제어 평면은 Google Cloud NetApp Volumes 관리자와 NetApp 기본 자동화 소프트웨어가 관리하는 백엔드 인프라입니다.  이 플레인은 최종 사용자에게 완전히 투명하며 네트워킹, 스토리지 하드웨어, 소프트웨어 업데이트 등을 포함하여 Google Cloud NetApp Volumes 와 같은 클라우드 상주 솔루션에 가치를 제공하는 데 도움이 됩니다.



== 데이터 플레인

Google Cloud NetApp Volumes 의 데이터 플레인에는 실제 데이터 볼륨과 전반적인 Google Cloud NetApp Volumes 구성(액세스 제어, Kerberos 인증 등)이 포함됩니다.  데이터 플레인은 전적으로 Google Cloud NetApp Volumes 플랫폼의 최종 사용자와 소비자의 제어를 받습니다.

각 항공기의 보안 및 관리 방법에는 뚜렷한 차이가 있습니다.  다음 섹션에서는 Google Cloud NetApp Volumes 아키텍처 개요부터 시작하여 이러한 차이점에 대해 설명합니다.
